"""Remove dummy column-1

Revision ID: 8653891bca42
Revises: 215e21b71a24
Create Date: 2024-09-09 17:57:03.438365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8653891bca42'
down_revision = '215e21b71a24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guest', schema=None) as batch_op:
        batch_op.drop_column('dummy_column')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guest', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dummy_column', sa.VARCHAR(length=50), nullable=True))

    # ### end Alembic commands ###
